import { promises as fs } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
const root=process.cwd(),failures=[];const pass=m=>console.log(`PASS  ${m}`),fail=m=>{failures.push(m);console.error(`FAIL  ${m}`)};
async function exists(f){try{await fs.access(path.join(root,f));return true}catch{return false}}async function read(f){return fs.readFile(path.join(root,f),"utf8")}
async function walk(d){const out=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(["node_modules",".next",".git"].includes(e.name))continue;const p=path.join(d,e.name);e.isDirectory()?out.push(...await walk(p)):out.push(p)}return out}
function has(content,regex,label){regex.lastIndex=0;regex.test(content)?pass(label):fail(label)}
const required=["README.md","PROJECT_SETUP_GUIDE.md","SUPABASE_SETUP_GUIDE.md","STRIPE_SETUP_GUIDE.md","KNOWLEDGE_BASE_GUIDE.md","ADMIN_GUIDE.md","NETLIFY_DEPLOYMENT_GUIDE.md","EMBED_WIDGET_GUIDE.md","FUTURE_PRODUCTS.md","BILLING_ARCHITECTURE_RESEARCH.md","COMPLETE_BILLING_SETUP_GUIDE.md","PRODUCTION_DEPLOYMENT_CHECKLIST.md","src/contexts/AuthContext.tsx","src/app/pricing/page.tsx","src/app/dashboard/history/page.tsx","src/app/admin/glossary/page.tsx","src/app/admin/plans/page.tsx","src/app/admin/widgets/page.tsx","src/app/dashboard/widget/page.tsx","public/tun-translator-widget.js","examples/widget-host-test.html","src/app/robots.ts","src/app/sitemap.ts","src/app/admin/queries/page.tsx","src/app/admin/subscriptions/page.tsx","src/app/admin/payments/page.tsx","src/app/dashboard/billing/page.tsx","supabase/migrations/20260804000200_commercial_mvp.sql","supabase/migrations/20260805000100_complete_billing_portal.sql","supabase/migrations/20260805000200_production_branding_and_plan_admin.sql","supabase/migrations/20260805000300_embed_widget_and_manual_plan_overrides.sql","supabase/migrations/20260813000100_translation_speed_and_language_expansion.sql","src/lib/western-armenian-transliteration.ts","supabase/functions/translate/index.ts","supabase/functions/widget-translate/index.ts","supabase/functions/stripe-checkout/index.ts","supabase/functions/stripe-portal/index.ts","supabase/functions/stripe-webhook/index.ts","supabase/functions/stripe-admin/index.ts","supabase/functions/delete-account/index.ts","knowledge-base-templates/glossary-template.csv"];
for(const f of required)(await exists(f))?pass(`${f} exists`):fail(`${f} missing`);
const pkg=JSON.parse(await read("package.json"));for(const d of ["next","react","react-dom","@supabase/supabase-js","openai"])pkg.dependencies?.[d]?pass(`${d} declared`):fail(`${d} missing`);for(const s of ["dev","build","lint","test","verify","zip","production:check","supabase:db:push","supabase:functions:deploy"])pkg.scripts?.[s]?pass(`script ${s}`):fail(`script ${s} missing`);
const env=await read(".env.example");has(env,/NEXT_PUBLIC_SUPABASE_URL=/u,"public Supabase URL documented");has(env,/NEXT_PUBLIC_BILLING_ENABLED=false/u,"billing-disabled frontend default");if(/OPENAI_API_KEY\s*=\s*sk-/u.test(env))fail("root env contains key");else pass("root env has no OpenAI key");
const edgeEnv=await read("supabase/functions/.env.example");for(const v of ["OPENAI_API_KEY","OPENAI_MODEL","BILLING_ENABLED","STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET","SITE_URL"])has(edgeEnv,new RegExp(`^${v}=`,"mu"),`${v} documented for Edge Functions`);
const migration=await read("supabase/migrations/20260804000200_commercial_mvp.sql");for(const t of ["plans","profiles","subscriptions","translation_history","translation_feedback","monthly_usage","stripe_webhook_events"])has(migration,new RegExp(`public\\.${t}`,"u"),`${t} schema included`);for(const f of ["find_translation_context","increment_monthly_usage","admin_dashboard_stats","handle_new_user"])has(migration,new RegExp(f,"u"),`${f} function included`);has(migration,/enable row level security/iu,"RLS enabled");
const translate=await read("supabase/functions/translate/index.ts");for(const x of ["resolveAccount","monthlyCharacterLimit","maxCharactersPerRequest","consumeRateLimit","findRelevantContext","increment_monthly_usage","saveHistory","translateWithOpenAI"])has(translate,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"u"),`translate includes ${x}`);
const openaiShared=await read("supabase/functions/_shared/openai-translation.ts");has(openaiShared,/\.responses\.create/u,"shared OpenAI Responses call");has(openaiShared,/store:\s*false/u,"OpenAI response storage disabled");
const webhook=await read("supabase/functions/stripe-webhook/index.ts");has(webhook,/constructStripeEvent/u,"Stripe signature verification");has(webhook,/stripe_webhook_events/u,"Stripe idempotency table");
const phase3=await read("supabase/migrations/20260805000100_complete_billing_portal.sql");for(const t of ["billing_payments","admin_audit_log","query_review_consent","admin_commercial_stats"])has(phase3,new RegExp(t,"u"),`Phase 3 includes ${t}`);

const widgetMigration=await read("supabase/migrations/20260805000300_embed_widget_and_manual_plan_overrides.sql");for(const x of ["user_plan_overrides","widget_sites","widget_usage_events","effective_plan_for_user","admin_set_user_plan_override","manage_widget_site","admin_widget_sites"])has(widgetMigration,new RegExp(x,"u"),`widget/manual migration includes ${x}`);
const widgetEdge=await read("supabase/functions/widget-translate/index.ts");for(const x of ["originMatchesDomain","resolveEffectivePlan","findRelevantContext","buildTranslationInstructions","translateWithOpenAI","widget_usage_events"])has(widgetEdge,new RegExp(x,"u"),`widget translate includes ${x}`);
const widgetScript=await read("public/tun-translator-widget.js");has(widgetScript,/attachShadow/u,"widget uses Shadow DOM");if(/innerHTML/u.test(widgetScript))fail("widget uses innerHTML");else pass("widget avoids innerHTML");
const deployScript=pkg.scripts?.["supabase:functions:deploy"]||"";has(deployScript,/widget-translate/u,"deployment script includes widget-translate");
const speedMigration=await read("supabase/migrations/20260813000100_translation_speed_and_language_expansion.sql");for(const x of ["prepare_translation_request","prepare_translation_account","translation_account_for_user","anonymous_translation_plan","en' and target_language = 'hye","hye' and target_language = 'en"])has(speedMigration,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"u"),`speed/language migration includes ${x}`);
const clientLanguages=await read("src/lib/languages.ts");for(const x of ['{ source: "en", target: "hye" }','{ source: "hye", target: "en" }'])has(clientLanguages,new RegExp(x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"u"),`client language pairs include ${x}`);
const transliteration=await read("src/lib/western-armenian-transliteration.ts");has(transliteration,/կ:\s*"g"/u,"Western Armenian transliteration uses կ → g");
const all=await walk(root);
const productionMigration=await read("supabase/migrations/20260805000200_production_branding_and_plan_admin.sql");for(const x of ["anonymous_usage","plans_admin_write","get_public_translation_settings"])has(productionMigration,new RegExp(x,"u"),`production migration includes ${x}`);
const header=await read("src/components/Header.tsx");has(header,/Tun-Logo_Web-Black_80\.png/u,"official Tun logo configured");
const layout=await read("src/app/layout.tsx");has(layout,/cropped-Tun_Site-Icon-192x192\.png/u,"official Tun favicon configured");
const adminPlans=await read("src/app/admin/plans/page.tsx");for(const x of ["Anonymous visitor limits","WooCommerce billing","Save visitor limits"])has(adminPlans,new RegExp(x,"u"),`plan admin includes ${x}`);
const checkout=await read("supabase/functions/stripe-checkout/index.ts");for(const x of ["stripe_price_id","unit_amount","recurring"])has(checkout,new RegExp(x,"u"),`checkout validates ${x}`);
const uiFiles=all.filter(f=>/\.(?:ts|tsx|css)$/u.test(f)&&f.includes(`${path.sep}src${path.sep}`));for(const file of uiFiles){const c=await fs.readFile(file,"utf8");if(/Commercial MVP|Human review recommended|Expert review recommended|AI translations may contain errors|Text is securely sent through Supabase/u.test(c))fail(`production copy remains in ${path.relative(root,file)}`)}
let secret=false;for(const file of all.filter(f=>/\.(?:ts|tsx|js|mjs|json|md|css|toml|sql|csv|example)$/u.test(f)||path.basename(f).startsWith(".env"))){const c=await fs.readFile(file,"utf8");if(/\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/u.test(c)){secret=true;fail(`possible OpenAI key in ${path.relative(root,file)}`)}}if(!secret)pass("no OpenAI key pattern found");
const candidates=[path.join(root,"node_modules/typescript/lib/typescript.js"),"/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript/lib/typescript.js"];let tsp;for(const c of candidates)try{await fs.access(c);tsp=c;break}catch{}
if(tsp){const mod=await import(pathToFileURL(tsp).href),ts=mod.default??mod;let syntax=0;for(const file of all.filter(f=>/\.(?:ts|tsx)$/u.test(f)&&!f.endsWith(".d.ts"))){const r=ts.transpileModule(await fs.readFile(file,"utf8"),{fileName:file,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,jsx:ts.JsxEmit.ReactJSX,isolatedModules:true}});for(const d of r.diagnostics??[])if(d.category===ts.DiagnosticCategory.Error){syntax++;fail(`${path.relative(root,file)}: ${ts.flattenDiagnosticMessageText(d.messageText," ")}`)}}if(!syntax)pass("all TypeScript/TSX files pass syntax transpilation")}
if(failures.length){console.error(`\nVerification failed: ${failures.length}`);process.exit(1)}console.log("\nProject source verification passed.");
